# syntax = docker/dockerfile:1.2
FROM clojure:openjdk-17 AS build

WORKDIR /

RUN apt-get install -yq npm

# RUN apt-cache search curl
# RUN apt-get install libcurl3-gnutls

# install from nodesource using apt-get
# RUN /usr/bin/curl -sL https://deb.nodesource.com/setup | bash - && apt-get install -yq nodejs build-essential

RUN npm install

RUN npx shadow-cljs compile frontend

COPY . /

RUN clj -Sforce -T:build all

FROM azul/zulu-openjdk-alpine:17

COPY --from=build /target/exerciser-standalone.jar /exerciser/exerciser-standalone.jar

EXPOSE 3000

ENTRYPOINT exec java $JAVA_OPTS -jar /exerciser/exerciser-standalone.jar
